# When the calendar begins and how long it runs
start_day: 2025-09-01
horizon_days: 14

# (Optional) process precedence pairs. If omitted, it defaults to chain P1->P2->P3->P4
precedence:
  - [1, 2]
  - [2, 3]
  - [3, 4]

# Tasks: workload = total person-days; daily_max = capacity per day; deadline = YYYY-MM-DD
tasks:
  - code: P1-A
    workload: 3
    daily_max: 2
    deadline: 2025-09-03
  - code: P1-B
    workload: 2
    daily_max: 2
    deadline: 2025-09-03
  - code: P1-C
    workload: 2
    daily_max: 1
    deadline: 2025-09-04
  - code: P1-D
    workload: 3
    daily_max: 2
    deadline: 2025-09-05

  - code: P2-A
    workload: 3
    daily_max: 2
    deadline: 2025-09-07
  - code: P2-B
    workload: 2
    daily_max: 1
    deadline: 2025-09-07
  - code: P2-C
    workload: 2
    daily_max: 1
    deadline: 2025-09-08
  - code: P2-D
    workload: 3
    daily_max: 2
    deadline: 2025-09-09

# Employees and their levels PER TASK CODE (1..5). Missing entries default to level 1.
employees:
  - name: Ann
    skills: { P1-A: 4, P1-B: 3, P1-C: 2, P1-D: 5, P2-A: 4, P2-B: 3 }
  - name: Beth
    skills: { P1-A: 2, P1-B: 3, P1-C: 4, P1-D: 1, P2-A: 3, P2-C: 5 }
  - name: Chad
    skills: { P1-A: 1, P1-B: 2, P1-C: 5, P1-D: 4, P2-A: 2, P2-D: 4 }
  - name: Dai
    skills: { P1-A: 5, P1-B: 2, P1-C: 3, P1-D: 2, P2-A: 5, P2-B: 2 }
  - name: Emi
    skills: { P1-A: 3, P1-B: 4, P1-C: 1, P1-D: 3, P2-A: 2, P2-B: 4 }
  - name: Faye
    skills: { P1-A: 2, P1-B: 1, P1-C: 2, P1-D: 5, P2-A: 4, P2-D: 3 }
  - name: Gus
    skills: { P1-A: 1, P1-B: 5, P1-C: 3, P1-D: 4, P2-A: 1, P2-C: 2 }
  - name: Hiro
    skills: { P1-A: 4, P1-B: 2, P1-C: 3, P1-D: 3, P2-A: 2, P2-C: 4 }
