// English UI strings. To switch the app to English, change uiConfig.ts to:
//   export { UI } from './uiConfig.en';
// (Default is Japanese; see uiConfig.ts.)

export const UI = {
  app: {
    title: ' Scheduler',
    subtitle: 'Employee Schedule Optimizer',
  },

  sidebar: {
    runLog: 'Run Log',
    settings: 'Settings',
  },

  runLog: {
    heading: 'Run Log',
    subheading: ' solve history',
    newRun: 'New Run',
    columnDate: 'Solve Date',
    columnInput: 'Input Files',
    columnResult: 'Result',
    columnActions: '',
    // Buttons
    showCopyBtn: 'Show Copy File',
    showResultBtn: 'Show Result',
    deleteBtn: 'Delete',
    cancelBtn: 'Cancel',
    fetching: 'Checking…',
    filesReady: 'Files ready',
    outputEmpty: '(no output yet)',
    // Path popup labels
    originalEnvLabel: 'Original EnvConfig Path',
    originalSchedLabel: 'Original Schedule Path',
    savedEnvLabel: 'Saved EnvConfig Path',
    savedSchedLabel: 'Saved Schedule Path',
    savedOutputLabel: 'Saved Output Path',
    pathUnknown: '(not provided)',
    // New Run modal
    modalTitle: 'New Run',
    modalHint: 'Drag-and-drop or click to select the two YAML files. Each file will be copied into public/local/<runId>/input/. Optionally paste the file’s original disk path so it shows up in the hover popup.',
    envLabel: 'EnvConfig.yaml',
    envHint: 'YAML — worker definitions, regions, workflows',
    schedLabel: 'Schedule.yaml',
    schedHint: 'YAML — tasks, plan range, assignments',
    dropHint: 'Drop a YAML file here, or click to browse',
    dropHintActive: 'Release to upload',
    originalPathLabel: 'Original Path (optional)',
    originalPathPlaceholder: 'e.g. C:/work/inputs/EnvConfig.yaml',
    selectFile: 'Click to select',
    fileSelected: 'File selected',
    submit: 'Submit Run',
    cancel: 'Cancel',
    uploading: 'Uploading…',
    uploadError: 'Upload failed:',
    uploadDoneTitle: 'Upload completed',
    uploadDoneBodyLocal: 'Input files were saved successfully.',
    uploadDoneBodyApi: 'Input files were saved and API submission was sent.',
    uploadDoneClose: 'Close',
    // Gantt editor placeholder dialog
    ganttDialogTitle: 'Gantt Editor',
    ganttDialogBody: 'This will open the Gantt editor tool (built by another team). Not connected yet — this is a placeholder.',
    ganttDialogClose: 'Close',
    // Result-not-ready dialog (local-only mode)
    notReadyTitle: 'Result not available',
    notReadyBody: 'No output file found in public/local/<id>/output/ and Azure Blob Storage is not connected yet. Either the solve hasn\'t finished, or the run id is invalid.',
    notReadyClose: 'Close',
    // Solver status dialog (when VITE_API_BASE_URL is set)
    solverStatusTitle: 'Solve in progress',
    solverStatusSubmitted: 'The run is queued and waiting to start.',
    solverStatusRunning: 'Solver is still running.',
    solverStatusCancelled: 'This run was cancelled.',
    solverCompletedTitle: 'Solve completed',
    solverCompletedBody: 'You can download the result file now.',
    solverCompletedDownload: 'Download',
    solverCompletedCancel: 'Close',
    solverFailedTitle: 'Solver failed',
    solverFailedLabel: 'Error:',
    solverFailedUnknown: 'No error detail was recorded.',
    solverErrorTitle: 'Service error',
    solverStatusClose: 'Close',
    incomingTransferErrorTitle: 'Failed to receive data from GanttChartEditor',
    // Delete confirm dialog (output yaml exists — run is finished)
    deleteConfirmTitle: 'Delete this run?',
    deleteConfirmBody: 'This will remove the row and delete public/local/<id>/ on disk. This cannot be undone.',
    deleteConfirmYes: 'Delete',
    deleteConfirmNo: 'Cancel',
    // Cancel confirm dialog (output yaml NOT yet present — run still in progress)
    cancelConfirmTitle: 'Cancel this run?',
    cancelConfirmBody: 'This will cancel the running  process AND remove the row + public/local/<id>/ on disk. This cannot be undone.',
    cancelConfirmYes: 'Cancel run',
    cancelConfirmNo: 'Keep',
  },

  dataList: {
    heading: 'Datasets',
    subheading: 'All schedule datasets and their solve history.',
    columnId: 'Dataset ID',
    columnName: 'Name',
    columnDesc: 'Description',
    columnRuns: 'Runs',
    columnStatus: 'Latest Status',
    columnUpdated: 'Updated',
    noData: 'No datasets found.',
    loadError: 'Failed to load datasets.',
  },

  detail: {
    backLabel: 'Datasets',
    sectionRuns: 'Solve Runs',
    sectionComments: 'Comments',
    columnRun: 'Run #',
    columnLabel: 'Label',
    columnStatus: 'Status',
    columnStarted: 'Started',
    columnTime: 'Executed Time',
    columnOutput: 'Output',
    noRuns: 'No runs yet.',
    viewGantt: 'View Gantt',
    downloadExcel: 'Download Excel',
    commentPlaceholder: 'Add a comment…',
    commentAdd: 'Add',
    commentEmpty: 'No comments yet.',
    totalRuns: 'Total Runs',
    latestStatus: 'Latest Status',
  },

  gantt: {
    heading: 'Gantt Chart',
    backLabel: 'Run Log',
    downloadExcel: 'Download Excel',
    legendUnavailable: 'Unavailable',
    legendCutoff: 'Cut-off date',
    legendToday: 'Today',
    legendWeekend: 'Weekend',
    editMode: 'Edit Mode',
    editModeOff: 'View Mode',
    sectionConstraints: 'Constraint Violations',
    noViolations: 'No violations.',
    loadError: 'Failed to load schedule data.',
    mockNote: 'Mock schedule — no real YAML for this run.',
    viewInput: 'Input schedule',
    viewResult: 'Result schedule',
    newRunTitle: 'New Run',
    reuseLabel: 'Reusing input files',
    planStart: 'Plan Start',
    planEnd: 'Plan End',
    cutoff: 'Cut-off Date',
    cutoffHint: 'Fixed-zone boundary',
    stageLabel: 'Solver Stage',
    stage1: 'Stage 1 only',
    stage1Time: '(~10 min)',
    stage12: 'Stage 1 + 2',
    stage12Time: '(~3 hr)',
    optLock: 'Lock all assignments before cut-off (do not reassign fixed zone)',
    optWarm: 'Use this result as warm start',
    optOvertime: 'Allow overtime (relax monthly overtime constraint to soft)',
    review: 'Review & Confirm',
    back: 'Back',
    submit: 'Submit Run',
    readyToSubmit: 'Ready to submit',
    submittedTitle: 'Run submitted.',
    submittedBody: 'A new local run folder was created. Come back to the Run Log to fetch results when the solver completes.',
    backToLog: 'Back to Run Log',
  },

  newRun: {
    heading: 'New Run',
    subheading: 'Configure and submit a new solver run.',
    step1: 'Source Data',
    step2: 'Plan Settings',
    step3: 'Review & Submit',
    srcExistTitle: 'Use Existing Dataset',
    srcExistDesc: 'Select a previously uploaded dataset.',
    srcNewTitle: 'Upload New Files',
    srcNewDesc: 'Upload EnvConfig.yaml and Schedule.yaml.',
    mergeNote: 'Both sources selected —  will merge them (2 × EnvConfig + 2 × Schedule).',
    labelExistDataset: 'Dataset',
    labelEnvConfig: 'EnvConfig.yaml',
    labelSchedule: 'Schedule.yaml',
    labelPlanStart: 'Plan Start',
    labelPlanEnd: 'Plan End',
    labelCutoff: 'Cut-off Date',
    labelLabel: 'Run Label',
    labelDuration: 'Solve Duration (minutes)',
    labelOvertime: 'Allow Overtime',
    sectionJobOrders: 'Additional Job Orders',
    addJobOrder: '+ Add Job Order',
    submit: 'Submit Run',
    back: 'Back',
    next: 'Next',
    review: 'Review',
  },

  status: {
    Completed: 'Completed',
    Failed: 'Failed',
    Executing: 'Executing',
    none: '—',
  },
} as const;