// Japanese UI strings. This is the active language by default — see uiConfig.ts.
// To switch to English: in uiConfig.ts, change the re-export to './uiConfig.en'.

export const UI = {
  app: {
    title: ' スケジューラ',
    subtitle: '従業員スケジュール最適化',
  },

  sidebar: {
    runLog: '実行ログ',
    settings: '設定',
  },

  runLog: {
    heading: '実行ログ',
    subheading: ' ソルブ履歴',
    newRun: '新規実行',
    columnDate: '実行日時',
    columnInput: '入力ファイル',
    columnResult: '結果',
    columnActions: '',
    // Buttons
    showCopyBtn: 'コピーファイル表示',
    showResultBtn: '結果を表示',
    deleteBtn: '削除',
    cancelBtn: 'キャンセル',
    fetching: '確認中…',
    filesReady: 'ファイル準備完了',
    outputEmpty: '(出力なし)',
    // Path popup labels
    originalEnvLabel: 'EnvConfig 元パス',
    originalSchedLabel: 'Schedule 元パス',
    savedEnvLabel: 'EnvConfig 保存先パス',
    savedSchedLabel: 'Schedule 保存先パス',
    savedOutputLabel: '出力 保存先パス',
    pathUnknown: '(未指定)',
    // New Run modal
    modalTitle: '新規実行',
    modalHint: '2 つの YAML ファイルをドラッグ&ドロップ、またはクリックして選択してください。各ファイルは public/local/<runId>/input/ にコピーされます。任意で元のディスクパスを貼り付けると、ホバー時のポップアップに表示されます。',
    envLabel: 'EnvConfig.yaml',
    envHint: 'YAML — 作業者定義、地域、ワークフロー',
    schedLabel: 'Schedule.yaml',
    schedHint: 'YAML — タスク、計画範囲、割り当て',
    dropHint: 'YAML ファイルをここにドロップ、またはクリックして選択',
    dropHintActive: '離してアップロード',
    originalPathLabel: '元パス (任意)',
    originalPathPlaceholder: '例: C:/work/inputs/EnvConfig.yaml',
    selectFile: 'クリックして選択',
    fileSelected: 'ファイル選択済み',
    submit: '実行を投入',
    cancel: 'キャンセル',
    uploading: 'アップロード中…',
    uploadError: 'アップロード失敗:',
    uploadDoneTitle: 'アップロード完了',
    uploadDoneBodyLocal: '入力ファイルの保存が完了しました。',
    uploadDoneBodyApi: '入力ファイルの保存と API 送信が完了しました。',
    uploadDoneClose: '閉じる',
    // Gantt editor placeholder dialog
    ganttDialogTitle: 'ガントチャートエディタ',
    ganttDialogBody: '別チームが開発予定のガントチャートエディタが開きます。現在は未接続のためプレースホルダーです。',
    ganttDialogClose: '閉じる',
    // Result-not-ready dialog (ローカル専用モード)
    notReadyTitle: '結果が利用できません',
    notReadyBody: 'public/local/<id>/output/ に出力ファイルが見つからず、Azure Blob Storage はまだ接続されていません。ソルブが未完了か、実行 ID が無効です。',
    notReadyClose: '閉じる',
    // Solver status dialog (VITE_API_BASE_URL が設定されている場合)
    solverStatusTitle: 'ソルブ実行中',
    solverStatusSubmitted: '実行はキューに入り、開始待ちです。',
    solverStatusRunning: 'ソルバはまだ実行中です。',
    solverStatusCancelled: 'この実行はキャンセル済みです。',
    solverCompletedTitle: 'ソルブ完了',
    solverCompletedBody: '結果ファイルをダウンロードできます。',
    solverCompletedDownload: 'ダウンロード',
    solverCompletedCancel: '閉じる',
    solverFailedTitle: 'ソルバが失敗しました',
    solverFailedLabel: 'エラー:',
    solverFailedUnknown: 'エラー詳細が記録されていません。',
    solverErrorTitle: 'サービスエラー',
    solverStatusClose: '閉じる',
    incomingTransferErrorTitle: 'GanttChartEditorからのデータ受信に失敗しました',
    // Delete confirm dialog (output yaml が存在 — 実行完了済み)
    deleteConfirmTitle: 'この実行を削除しますか?',
    deleteConfirmBody: 'この行を削除し、public/local/<id>/ をディスクから削除します。この操作は取り消せません。',
    deleteConfirmYes: '削除',
    deleteConfirmNo: 'いいえ',
    // Cancel confirm dialog (output yaml が未生成 — 実行中)
    cancelConfirmTitle: 'この実行をキャンセルしますか?',
    cancelConfirmBody: '進行中の  プロセスをキャンセルし、この行および public/local/<id>/ をディスクから削除します。この操作は取り消せません。',
    cancelConfirmYes: '実行をキャンセル',
    cancelConfirmNo: '続行',
  },

  dataList: {
    heading: 'データセット',
    subheading: '全スケジュールデータセットとソルブ履歴。',
    columnId: 'データセット ID',
    columnName: '名前',
    columnDesc: '説明',
    columnRuns: '実行数',
    columnStatus: '最新ステータス',
    columnUpdated: '更新日時',
    noData: 'データセットがありません。',
    loadError: 'データセットの読み込みに失敗しました。',
  },

  detail: {
    backLabel: 'データセット',
    sectionRuns: 'ソルブ実行',
    sectionComments: 'コメント',
    columnRun: '実行 #',
    columnLabel: 'ラベル',
    columnStatus: 'ステータス',
    columnStarted: '開始',
    columnTime: '実行時間',
    columnOutput: '出力',
    noRuns: 'まだ実行がありません。',
    viewGantt: 'ガントチャート表示',
    downloadExcel: 'Excel ダウンロード',
    commentPlaceholder: 'コメントを追加…',
    commentAdd: '追加',
    commentEmpty: 'まだコメントがありません。',
    totalRuns: '合計実行数',
    latestStatus: '最新ステータス',
  },

  gantt: {
    heading: 'ガントチャート',
    backLabel: '実行ログ',
    downloadExcel: 'Excel ダウンロード',
    legendUnavailable: '利用不可',
    legendCutoff: '締切日',
    legendToday: '本日',
    legendWeekend: '週末',
    editMode: '編集モード',
    editModeOff: '閲覧モード',
    sectionConstraints: '制約違反',
    noViolations: '違反なし。',
    loadError: 'スケジュールデータの読み込みに失敗しました。',
    mockNote: 'モックスケジュール — この実行には実 YAML がありません。',
    viewInput: '入力スケジュール',
    viewResult: '結果スケジュール',
    newRunTitle: '新規実行',
    reuseLabel: '入力ファイルを再利用',
    planStart: '計画開始日',
    planEnd: '計画終了日',
    cutoff: '締切日',
    cutoffHint: '固定ゾーン境界',
    stageLabel: 'ソルバステージ',
    stage1: 'Stage 1 のみ',
    stage1Time: '(約 10 分)',
    stage12: 'Stage 1 + 2',
    stage12Time: '(約 3 時間)',
    optLock: '締切前の全割り当てをロック (固定ゾーン再割り当て不可)',
    optWarm: 'この結果をウォームスタートとして使用',
    optOvertime: '残業を許可 (月次残業制約を soft に緩和)',
    review: '確認',
    back: '戻る',
    submit: '実行を投入',
    readyToSubmit: '投入準備完了',
    submittedTitle: '実行を投入しました。',
    submittedBody: '新規ローカル実行フォルダが作成されました。ソルバ完了後、実行ログから結果を取得してください。',
    backToLog: '実行ログへ戻る',
  },

  newRun: {
    heading: '新規実行',
    subheading: '新規ソルバ実行の設定と投入。',
    step1: 'ソースデータ',
    step2: '計画設定',
    step3: '確認 & 投入',
    srcExistTitle: '既存データセットを使用',
    srcExistDesc: 'アップロード済みデータセットから選択。',
    srcNewTitle: '新規ファイルをアップロード',
    srcNewDesc: 'EnvConfig.yaml と Schedule.yaml をアップロード。',
    mergeNote: '両ソース選択済み —  がマージします (EnvConfig × 2 + Schedule × 2)。',
    labelExistDataset: 'データセット',
    labelEnvConfig: 'EnvConfig.yaml',
    labelSchedule: 'Schedule.yaml',
    labelPlanStart: '計画開始日',
    labelPlanEnd: '計画終了日',
    labelCutoff: '締切日',
    labelLabel: '実行ラベル',
    labelDuration: 'ソルブ時間 (分)',
    labelOvertime: '残業許可',
    sectionJobOrders: '追加ジョブオーダー',
    addJobOrder: '+ ジョブオーダーを追加',
    submit: '実行を投入',
    back: '戻る',
    next: '次へ',
    review: '確認',
  },

  status: {
    Completed: '完了',
    Failed: '失敗',
    Executing: '実行中',
    none: '—',
  },
} as const;