
planning:
  start_date: 2025-09-01
  days: 14
  weekend_work: false

staffing_limits:
  min_per_task_per_day: 2
  max_per_task_per_day: 5

countries:
  A:
    visa_stay_limit: 4
    stay_gap_days: 3
    annual_limit: 10
    annual_break_days: 3
  B:
    visa_stay_limit: 5
    stay_gap_days: 3
    annual_limit: 10
    annual_break_days: 3

country_changeover_days:
  A: { A: 0, B: 2 }          
  B: { A: 2, B: 0 }


modules:
  - id: M1
    name: "Mock Module"
    processes:
      - id: P1
        name: "Mock Process"
        tasks:
          - id: T1
            name: "Task 1"
            country: A
            workload: 31 
          - id: T2
            name: "Task 2"
            country: B
            workload: 29
          - id: T3
            name: "Task 3"
            country: A
            workload: 32

# Lightweight employee list (≈15): AA .. AO
employees:
  - "AA"
  - "AB"
  - "AC"
  - "AD"
  - "AE"
  - "AF"
  - "AG"
  - "AH"
  - "AI"
  - "AJ"
  - "AK"
  - "AL"
  - "AM"
  - "AN"
  - "AO"