import { useEffect, useRef, useState } from 'react';
import { AppProvider, useAppContext } from './context/AppContext';
import { GanttPage } from './pages/GanttPage';
import { ErrorDialog } from './components/Dialogs/ErrorDialog';
import { TaskAddDialog } from './components/Dialogs/TaskAddDialog';
import { NewScheduleDialog } from './components/Dialogs/NewScheduleDialog';
import { ConstraintResultDialog } from './components/Dialogs/ConstraintResultDialog';
import { SendToSchedulerDialog } from './components/Dialogs/SendToSchedulerDialog';
import { SessionDialog } from './components/Dialogs/SessionDialog';
import { useKeyboardShortcuts } from './hooks/useKeyboardShortcuts';
import { useConstraintCheck } from './hooks/useConstraintCheck';
import { useIncomingGanttTransfer } from './hooks/useIncomingGanttTransfer';
import { fetchSessionName } from './services/collabService';
import { UI } from './config/uiText';
import { SessionRole } from './types/appState';

// A link generated by "Start Session"/"Join Session" lands here
// (?session=<id>&role=edit|view) — opened by anyone on the network, in a
// plain browser, no login/build required.
function getSessionParamsFromUrl(): { sessionId: string; role: SessionRole } | null {
  const params = new URLSearchParams(window.location.search);
  const sessionId = params.get('session');
  if (!sessionId) return null;
  return { sessionId, role: params.get('role') === 'view' ? 'view' : 'edit' };
}

// The shared shell for every session role. Its hooks (global shortcuts,
// constraint checker, SchedulerWeb incoming-transfer listener) mount
// unconditionally; each one internally no-ops the specific actions a
// view-role participant shouldn't trigger, rather than the page deciding
// not to mount them at all — see useKeyboardShortcuts.ts and Toolbar.tsx.
function EditorShell() {
  useKeyboardShortcuts();
  useConstraintCheck();
  useIncomingGanttTransfer();
  return (
    <>
      <GanttPage />
      <TaskAddDialog />
      <NewScheduleDialog />
      <ConstraintResultDialog />
      <SendToSchedulerDialog />
      <SessionDialog />
      <ErrorDialog />
    </>
  );
}

// EditorShell is now shared by every role — a view-role participant gets the
// exact same page as an editor, with only the specific data-mutating
// interactions disabled (Toolbar/useKeyboardShortcuts here; the Gantt chart's
// own drag handlers in a later task). This replaced an earlier, separate
// read-only ViewPage that could only mirror — it couldn't scroll, filter, or
// run a constraint check, which real usage showed people wanted.
export function AppContent() {
  return <EditorShell />;
}

function SessionJoinGate({ sessionId, role }: { sessionId: string; role: SessionRole }) {
  const { joinCollabSession, state } = useAppContext();
  const [name, setName] = useState('');
  const [joining, setJoining] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sessionName, setSessionName] = useState<string | null>(null);

  // Best-effort label for the prompt title below — sessionId is fixed for
  // this gate's lifetime (it comes from the URL, not user typing), so a
  // single fetch on mount is enough; no debounce needed like the in-app
  // join dialog's lookup-as-you-type. A failed/unresolved lookup (bad id,
  // offline server) just leaves the generic fallback title in place —
  // fetchSessionName already swallows network errors into a null result.
  useEffect(() => {
    let cancelled = false;
    void fetchSessionName(sessionId).then(resolved => {
      if (!cancelled) setSessionName(resolved);
    });
    return () => { cancelled = true; };
  }, [sessionId]);
  // Tracks whether THIS join attempt has ever reached 'connected'. Only a
  // 'disconnected' seen before that point means the join itself failed (bad
  // id, unreachable server, sync-init {ok:false}) — a 'disconnected' seen
  // afterward is just a live session's connection blipping, which MenuBar's
  // participant count and view-only indicator already surface without
  // tearing down the editor/viewer underneath.
  const hasConnectedOnceRef = useRef(false);

  useEffect(() => {
    if (!joining) return;
    hasConnectedOnceRef.current = false;
    let cancelled = false;
    joinCollabSession(sessionId, name, role).catch(err => {
      if (!cancelled) setError(err instanceof Error ? err.message : UI.joinSessionErrorFallback);
    });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [joining]);

  // joinCollabSession's promise resolves as soon as the join request is sent —
  // it doesn't wait for the server's actual sync-init reply. A bad/expired
  // session id, or a connection that drops before it ever reaches 'connected',
  // only ever shows up asynchronously as connectionStatus flipping to
  // 'disconnected' (see collabService.ts's handleSyncInit/handleDisconnect).
  // SET_SESSION always seeds state.session with connectionStatus: 'connecting'
  // before this effect can run, so seeing 'disconnected' while joining is true
  // and the session has never yet connected can only mean a real failed join —
  // never an initial idle state. Once connected at least once, a later
  // 'disconnected' (a transient blip, or the host ending the session) is left
  // to the normal in-page UI rather than replacing it with a fatal screen.
  useEffect(() => {
    if (!joining) return;
    const status = state.session?.connectionStatus;
    if (status === 'connected') {
      hasConnectedOnceRef.current = true;
      return;
    }
    if (status === 'disconnected' && !hasConnectedOnceRef.current) {
      setError(UI.joinSessionErrorFallback);
    }
  }, [joining, state.session?.connectionStatus]);

  if (error) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'MS Gothic, monospace', color: '#c62828' }}>
        {error}
      </div>
    );
  }

  if (!joining) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'MS Gothic, monospace' }}>
        <form
          onSubmit={e => { e.preventDefault(); if (name.trim()) setJoining(true); }}
          style={{ display: 'flex', flexDirection: 'column', gap: 12, width: 280 }}
        >
          <div style={{ fontSize: 14, fontWeight: 'bold' }}>
            {sessionName ? UI.joinSessionPromptTitleNamed(sessionName) : UI.joinSessionPromptTitle}
          </div>
          <input
            autoFocus
            value={name}
            onChange={e => setName(e.target.value)}
            placeholder={UI.joinSessionNamePlaceholder}
            style={{ padding: '6px 8px', fontSize: 13, border: '1px solid #ccc', borderRadius: 4 }}
          />
          <button
            type="submit"
            disabled={!name.trim()}
            style={{ padding: '6px 12px', backgroundColor: '#1976d2', color: '#fff', border: 'none', borderRadius: 4, cursor: name.trim() ? 'pointer' : 'default' }}
          >
            {UI.joinSessionSubmitBtn}
          </button>
        </form>
      </div>
    );
  }

  // No role branch here: joinCollabSession has already seeded state.session
  // with this join's role, and AppContent makes the one read-only decision for
  // every entry point. (SET_SESSION is dispatched synchronously by the effect
  // above, so this resolves on the render right after `joining` flips.)
  return <AppContent />;
}

export default function App() {
  const sessionParams = getSessionParamsFromUrl();
  return (
    <AppProvider>
      {sessionParams
        ? <SessionJoinGate sessionId={sessionParams.sessionId} role={sessionParams.role} />
        : <AppContent />}
    </AppProvider>
  );
}
