import { useEffect, useState } from 'react';
import { AppProvider, useAppContext } from './context/AppContext';
import { GanttPage } from './pages/GanttPage';
import { ViewPage } from './pages/ViewPage';
import { ErrorDialog } from './components/Dialogs/ErrorDialog';
import { TaskAddDialog } from './components/Dialogs/TaskAddDialog';
import { NewScheduleDialog } from './components/Dialogs/NewScheduleDialog';
import { ConstraintResultDialog } from './components/Dialogs/ConstraintResultDialog';
import { SendToSchedulerDialog } from './components/Dialogs/SendToSchedulerDialog';
import { SessionDialog } from './components/Dialogs/SessionDialog';
import { useKeyboardShortcuts } from './hooks/useKeyboardShortcuts';
import { useConstraintCheck } from './hooks/useConstraintCheck';
import { useIncomingGanttTransfer } from './hooks/useIncomingGanttTransfer';
import { UI } from './config/uiText';
import { SessionRole } from './types/appState';

// A link generated by "Start Session"/"Join Session" lands here
// (?session=<id>&role=edit|view) — opened by anyone on the network, in a
// plain browser, no login/build required.
function getSessionParamsFromUrl(): { sessionId: string; role: SessionRole } | null {
  const params = new URLSearchParams(window.location.search);
  const sessionId = params.get('session');
  if (!sessionId) return null;
  return { sessionId, role: params.get('role') === 'view' ? 'view' : 'edit' };
}

function AppContent() {
  useKeyboardShortcuts();
  useConstraintCheck();
  useIncomingGanttTransfer();
  return (
    <>
      <GanttPage />
      <TaskAddDialog />
      <NewScheduleDialog />
      <ConstraintResultDialog />
      <SendToSchedulerDialog />
      <SessionDialog />
      <ErrorDialog />
    </>
  );
}

function SessionJoinGate({ sessionId, role }: { sessionId: string; role: SessionRole }) {
  const { joinCollabSession, state } = useAppContext();
  const [name, setName] = useState('');
  const [joining, setJoining] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!joining) return;
    let cancelled = false;
    joinCollabSession(sessionId, name, role).catch(err => {
      if (!cancelled) setError(err instanceof Error ? err.message : UI.joinSessionErrorFallback);
    });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [joining]);

  // joinCollabSession's promise resolves as soon as the join request is sent —
  // it doesn't wait for the server's actual sync-init reply. A bad/expired
  // session id, or a connection that drops before it ever reaches 'connected',
  // only ever shows up asynchronously as connectionStatus flipping to
  // 'disconnected' (see collabService.ts's handleSyncInit/handleDisconnect).
  // SET_SESSION always seeds state.session with connectionStatus: 'connecting'
  // before this effect can run, so seeing 'disconnected' while joining is true
  // can only mean a real failed/dropped join, never an initial idle state.
  useEffect(() => {
    if (!joining) return;
    if (state.session?.connectionStatus === 'disconnected') {
      setError(UI.joinSessionErrorFallback);
    }
  }, [joining, state.session?.connectionStatus]);

  if (error) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'MS Gothic, monospace', color: '#c62828' }}>
        {error}
      </div>
    );
  }

  if (!joining) {
    return (
      <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'MS Gothic, monospace' }}>
        <form
          onSubmit={e => { e.preventDefault(); if (name.trim()) setJoining(true); }}
          style={{ display: 'flex', flexDirection: 'column', gap: 12, width: 280 }}
        >
          <div style={{ fontSize: 14, fontWeight: 'bold' }}>{UI.joinSessionPromptTitle}</div>
          <input
            autoFocus
            value={name}
            onChange={e => setName(e.target.value)}
            placeholder={UI.joinSessionNamePlaceholder}
            style={{ padding: '6px 8px', fontSize: 13, border: '1px solid #ccc', borderRadius: 4 }}
          />
          <button
            type="submit"
            disabled={!name.trim()}
            style={{ padding: '6px 12px', backgroundColor: '#1976d2', color: '#fff', border: 'none', borderRadius: 4, cursor: name.trim() ? 'pointer' : 'default' }}
          >
            {UI.joinSessionSubmitBtn}
          </button>
        </form>
      </div>
    );
  }

  return role === 'view' ? <ViewPage /> : <AppContent />;
}

export default function App() {
  const sessionParams = getSessionParamsFromUrl();
  return (
    <AppProvider>
      {sessionParams
        ? <SessionJoinGate sessionId={sessionParams.sessionId} role={sessionParams.role} />
        : <AppContent />}
    </AppProvider>
  );
}
